---
name: Add Tutorials
title: "[ADD]: "
labels: ["add-tutorials"]
body:
- type: textarea
  id: what-happened
  attributes:
    label: "tutorials JSON list"
    description: "Copy here the json list of tutorials formatted as per docs"
    placeholder: "add json array here"
    value: "add json array here"
  validations:
    required: true

- type: checkboxes
  id: terms
  attributes:
    label: "Code of Conduct"
    description: "Confirm that the syntax is correct?"
    options:
      - label: "I confirm that I've provided useful content and not AI slop"
        required: true
---


